import itertools

tags =[
            "Ahegao",
            "Asphyxiation",
            "Big Areolae",
            "Big Breasts",
            "Big Penis",
            "Blowjob",
            "Bondage",
            "Burping",
            "Deepthroat",
            "Defloration",
            "Drugs",
            "Eye-covering Bang",
            "Full Color",
            "Glasses",
            "Gokkun",
            "Hairy",
            "Huge Breasts",
            "Kissing",
            "Muscle",
            "Nakadashi",
            "Paizuri",
            "Rough Translation",
            "Uncensored",
            "Virginity",
            "X-Ray",
            "Yandere",
            "Blowjob Face",
            "Condom",
            "Dark Sclera",
            "Elf",
            "Gloves",
            "High Heels",
            "Nurse",
            "Transformation",
            "Apron",
            "Big Ass",
            "Business Suit",
            "Cheating",
            "Cunnilingus",
            "DILF",
            "Handjob",
            "Impregnation",
            "MILF",
            "Mosaic Censorship",
            "Multi-Work Series",
            "Multipanel Sequence",
            "Netorare",
            "Sole Female",
            "Sole Male",
            "Squirting",
            "Tall Man",
            "Teacher",
            "FFM Threesome",
            "Gender Change",
            "Gender Morph",
            "Group",
            "Gyaru",
            "Multiple Paizuri",
            "Prostitution",
            "Schoolgirl Uniform",
            "Dark Skin",
            "Halo",
            "Ponytail",
            "Sex Toys",
            "Very Long Hair",
            "Wings",
            "Blackmail",
            "Bikini",
            "Swimsuit",
            "Anal",
            "Anal Intercourse",
            "Armpit Licking",
            "Double Penetration",
            "Leotard",
            "Magical Girl",
            "MMF Threesome",
            "Rape",
            "Femdom",
            "Full Censorship",
            "Kemonomimi",
            "Orgasm Denial",
            "Painted Nails",
            "Shotacon",
            "Tail",
            "Twintails",
            "Bodysuit",
            "Lactation",
            "Bald",
            "Cum Swap",
            "Daughter",
            "Incest",
            "Inseki",
            "Old Man",
            "Beauty Mark",
            "Breast Feeding",
            "Small Penis",
            "Demon Girl",
            "Horns",
            "Prostate Massage",
            "Collar",
            "Tall Girl",
            "Tomboy",
            "Nipple Stimulation",
            "Pixie Cut",
            "Blindfold",
            "Goblin",
            "Pregnant",
            "Witch",
            "Inverted Nipples",
            "Stockings",
            "Fingering",
            "Mother",
            "Shimaidon",
            "Unusual Pupils",
            "Clothed Paizuri",
            "Hair Buns",
            "Masturbation",
            "Chikan",
            "Corruption",
            "Hidden Sex",
            "Humiliation",
            "Mind Control",
            "Sweating",
            "Amputee",
            "Emotionless Sex",
            "Exposed Clothing",
            "Futanari",
            "Lingerie",
            "Low Scat",
            "Multiple Orgasms",
            "Nipple Piercing",
            "Piercing",
            "Ryona",
            "Stirrup Legwear",
            "Story Arc",
            "Thigh High Boots",
            "Yuri",
            "Pantyhose",
            "BBM",
            "Catgirl",
            "Large Tattoo",
            "Footjob",
            "Sister",
            "Crying",
            "Leash",
            "Mind Break",
            "Pig Man",
            "Aunt",
            "BBW",
            "Big Nipples",
            "Body Writing",
            "Bride",
            "Farting",
            "Gigantic Breasts",
            "Nose Hook",
            "Scat",
            "Slave",
            "Masked Face",
            "Solo Action",
            "Cosplaying",
            "Maid",
            "Tracksuit",
            "Females Only",
            "Saliva",
            "Twins",
            "vtuber",
            "Dickgirl on Male",
            "Full-packaged Futanari",
            "Shemale",
            "Sole Dickgirl",
            "Futanarization",
            "Inflation",
            "Tube",
            "Clit Stimulation",
            "Crotch Tattoo",
            "Eyepatch",
            "Machine",
            "Small Breasts",
            "Urination",
            "Bukkake",
            "Speculum",
            "Triple Penetration",
            "Urethra Insertion",
            "Filming",
            "Oni",
            "Monster",
            "Possession",
            "Dickgirl on Dickgirl",
            "Dickgirls Only",
            "Exhibitionism",
            "Facesitting",
            "Foot Licking",
            "Petplay",
            "Piss Drinking",
            "Smell",
            "Dog Girl",
            "Harem",
            "Multimouth Blowjob",
            "Sunglasses",
            "Bunny Girl",
            "Rimjob",
            "Nun",
            "Moral Degeneration",
            "Slime",
            "Bisexual",
            "Schoolboy Uniform",
            "Big Clit",
            "Fishnets",
            "Heterochromia",
            "First Person Perspective",
            "Tanlines",
            "Freckles",
            "Tankoubon",
            "Tentacles",
            "Cat",
            "Cowgirl",
            "Tail Plug",
            "Breast Expansion",
            "Fox Girl",
            "Assjob",
            "Cumflation",
            "Dickgirl On Female",
            "FFT Threesome",
            "Layer Cake",
            "Multiple Assjob",
            "Oyakodon",
            "Stomach Deformation",
            "CBT",
            "Cervix Penetration",
            "Domination Loss",
            "Foot Insertion",
            "Guro",
            "School Gym Uniform",
            "Chloroform",
            "Sleeping",
            "Body Modification",
            "Onahole",
            "Snuff",
            "Leg Lock",
            "Out of Order",
            "Kimono",
            "Pasties",
            "Vaginal Sticker",
            "Big Lips",
            "Robot",
            "Chinese Dress",
            "Living Clothes",
            "Parasite",
            "Vaginal Birth",
            "Cervix Prolapse",
            "Double Vaginal",
            "Fisting",
            "Gaping",
            "Nipple Fuck",
            "Prolapse",
            "Stretching",
            "Triple Vaginal",
            "Chastity Belt",
            "Clothed Female Nude Male",
            "Drill Hair",
            "Miniguy",
            "Sockjob",
            "Tickling",
            "Trampling",
            "Mesugaki",
            "No Penetration",
            "Long Tongue",
            "Oil",
            "Closed Eyes",
            "Thick Eyebrows",
            "Drunk",
            "Coach",
            "All The Way Through",
            "Focus Anal",
            "Garter Belt",
            "Hairy Armpits",
            "Scat Insertion",
            "Clone",
            "Bike Shorts",
            "Selfcest",
            "Enema",
            "Monster Girl",
            "Tailjob",
            "Tomgirl",
            "School Swimsuit",
            "Strap-On",
            "Dark Nipples",
            "Low Shotacon",
            "Furry",
            "Gyaru-Oh",
            "Makeup",
            "Insect",
            "Smalldom",
            "Milking",
            "Tiara",
            "Lab Coat",
            "Internal Urination",
            "Public Use",
            "Spanking",
            "Gag",
            "Voyeurism",
            "Cousin",
            "Squid Girl",
            "Torture",
            "Wrestling",
            "Omorashi",
            "Mouse Girl",
            "Smoking",
            "Shimapan",
            "Cheerleader",
            "Cock Ring",
            "Crossdressing",
            "Josou Seme",
            "Variant Set",
            "Forced Exposure",
            "Unusual Teeth",
            "Catfight",
            "Tribadism",
            "Low Incest",
            "Huge Penis",
            "Lolicon",
            "Feminization",
            "Male on Dickgirl",
            "Yaoi",
            "BDSM",
            "Apparel Bukkake",
            "Alien Girl",
            "Shibari",
            "Age Regression",
            "Facial Hair",
            "Gymshorts",
            "Smegma",
            "Nudity Only",
            "Stewardess",
            "Vomit",
            "Multiple Straddling",
            "Bestiality",
            "Low Bestiality",
            "Pig",
            "Scar",
            "Gang Rape",
            "Minigirl",
            "Males Only",
            "Bunny Boy",
            "Mesuiki",
            "Giantess",
            "Vampire",
            "Latex",
            "Vacbed",
            "Comic",
            "Low Lolicon",
            "Body Swap",
            "Goudoushi",
            "Skinsuit",
            "Large Insertions",
            "Niece",
            "Phimosis",
            "Cockslapping",
            "Monkey Boy",
            "Monkey Girl",
            "Shaved Head",
            "Ghost",
            "Breast Sucking",
            "Hotpants",
            "Dog",
            "Horse",
            "FFF Threesome",
            "Kunoichi",
            "Detached Sleeves",
            "Ball Sucking",
            "Brain Fuck",
            "Monoeye",
            "Multiple Arms",
            "Personality Excretion",
            "Stuck in Wall",
            "Soushuuhen",
            "Shared Senses",
            "Netorase",
            "Swinging",
            "Mouth Mask",
            "Armpit Sex",
            "Orc",
            "Denki Anma",
            "Ass Expansion",
            "Bloomers",
            "Navel Birth",
            "Lizard Girl",
            "Focus Paizuri",
            "Cum Bath",
            "Oppai Loli",
            "Cashier",
            "Widower",
            "Phone Sex",
            "Human Cattle",
            "Big Vagina",
            "Growth",
            "Penis Enlargement",
            "TTT Threesome",
            "Sheep Girl",
            "Eyemask",
            "Bodystocking",
            "Brother",
            "Redraw",
            "Transparent Clothing",
            "MMT Threesome",
            "TTF Threesome",
            "Handicapped",
            "Pegging",
            "Forbidden Content",
            "Policewoman",
            "Randoseru",
            "Frottage",
            "Incomplete",
            "Blood",
            "Electric Shocks",
            "harness",
            "Clothed Male Nude Female",
            "Nudism",
            "Kodomo Doushi",
            "Kodomo Only",
            "Kindergarten Uniform",
            "Ball Caressing",
            "Genital Piercing",
            "Metal Armor",
            "Double Anal",
            "Eggs",
            "Focus Blowjob",
            "Clit Growth",
            "Unbirth",
            "Compilation",
            "Grandmother",
            "Miko",
            "Sumata",
            "Petrification",
            "Age Progression",
            "Doll Joints",
            "Replaced",
            "Wolf Girl",
            "Monkey",
            "Glory Hole",
            "Kigurumi Pajama",
            "Multiple Penises",
            "Coprophagia",
            "Snake Girl",
            "3D",
            "Old Lady",
            "Corset",
            "Anorexic",
            "Fundoshi",
            "Tutor",
            "Widow",
            "Plant Girl",
            "Shrinking",
            "Vore",
            "Uncle",
            "Prehensile Hair",
            "Nipple Expansion",
            "Pubic Stubble",
            "Short Hair",
            "Bandaid",
            "Christmas",
            "Tights",
            "Midget",
            "Waitress",
            "Bandages",
            "Big Balls",
            "Already Uploaded",
            "Goat",
            "Human on Furry",
            "Absorption",
            "Slime Girl",
            "Big Muscles",
            "Angel",
            "Clothed Female Naked Male",
            "Hat",
            "Military",
            "Weight Gain",
            "Demon",
            "Pantyjob",
            "Time Stop",
            "MTF Threesome",
            "Shark Girl",
            "Syringe",
            "Rough Grammar",
            "Fox Boy",
            "Double Blowjob",
            "Table Masturbation",
            "Clit Insertion",
            "Zombie",
            "Navel Fuck",
            "Raccoon Girl",
            "Whip",
            "Wolf",
            "Wormhole",
            "Unusual Insertions",
            "Harpy",
            "Underwater",
            "Artbook",
            "Mouse Boy",
            "Sundress",
            "Wet Clothes",
            "Group Sex",
            "Scrotal Lingerie",
            "Spider Girl",
            "Voyeur",
            "Bear Girl",
            "Gothic Lolita",
            "Kneepit Sex",
            "Catboy",
            "Toddlercon",
            "Diaper",
            "Infantilism",
            "Balls Expansion",
            "Penis Birth",
            "Anthology",
            "Crown",
            "Haigure",
            "Pillory",
            "Childhood Friend",
            "Unicorn",
            "Autofellatio",
            "Invisible",
            "Minotaur",
            "Kappa",
            "Dragon",
            "Object Insertion Only",
            "Father",
            "MMM Threesome",
            "Confinement",
            "TTM Threesome",
            "Ninja",
            "Defaced",
            "SSBBM",
            "Albino",
            "Bird Girl",
            "How To",
            "Mecha Girl",
            "Scanmark",
            "Body Painting",
            "Anal Prolapse",
            "Autopaizuri",
            "Office Lady",
            "Lipstick Mark",
            "Missing Cover",
            "Squid Boy",
            "Insect Girl",
            "Multiple Breasts",
            "Loli",
            "Fairy",
            "Ear Fuck",
            "Hanging",
            "Necrophilia",
            "Nipple Birth",
            "Pettanko",
            "Menstruation",
            "Granddaughter",
            "Hairjob",
            "Headphones",
            "Watermarked",
            "Hood",
            "Clamp",
            "Dicknipples",
            "Centaur",
            "Butler",
            "Frog",
            "Pole Dancing",
            "Alien",
            "Snake",
            "Ponygirl",
            "Lizard Guy",
            "No Balls",
            "Wolf Boy",
            "Worm",
            "Forniphilia",
            "Dougi",
            "Horse Cock",
            "Cowman",
            "Raccoon Boy",
            "Low Smegma",
            "Wooden Horse",
            "Pig Girl",
            "Squirrel Girl",
            "SSBBW",
            "Rabbit",
            "Anal Birth",
            "Triple Anal",
            "Merman",
            "Headless",
            "Mermaid",
            "Slug",
            "Legjob",
            "Adventitious Mouth",
            "Balljob",
            "Breast Reduction",
            "Fanny Packing",
            "Mouse",
            "Bat",
            "Low Guro",
            "Insect Boy",
            "Turtle",
            "Maggot",
            "Snail Girl",
            "Bee Girl",
            "Ugly Bastard",
            "Sarashi",
            "Horse Girl",
            "Eel",
            "Cuntboy",
            "Cannibalism",
            "Giant",
            "Cockphagia",
            "Blind",
            "Squirrel Boy",
            "Sample",
            "Pirate",
            "Abortion",
            "Gorilla",
            "Novel",
            "Gangbang",
            "Waiter",
            "Priest",
            "Nazi",
            "Horse Boy",
            "Cum in Eye",
            "Vomiting",
            "Slime Boy",
            "Tsundere",
            "Dog Boy",
            "Multiple Handjob",
            "Mute",
            "Schoolgirl",
            "Conjoined",
            "Panda Girl",
            "Dolphin",
            "Bat Girl",
            "Adventitious Vagina",
            "Giant Sperm",
            "Cow",
            "Reptile",
            "Cosplay",
            "Bull",
            "Sheep Boy",
            "Gasmask",
            "Animegao",
            "Wingjob",
            "Frog Girl",
            "Policeman",
            "Spider",
            "Race Queen",
            "Nose Fuck",
            "Orgasm Torture",
            "Analphagia",
            "Webtoon",
            "Creampie",
            "Octopus",
            "Ai Generated",
            "Tailphagia",
            "Succubus",
            "Adventitious Penis",
            "Pegasus",
            "Otokofutanari",
            "Straight Shota",
            "Cuntbusting",
            "Tiger",
            "Sole Pussyboy",
            "Hijab",
            "Oral",
            "Fox",
            "Animated",
            "Muscle Growth",
            "Clown",
            "Animal Ears",
            "Tooth Brushing",
            "Afro",
            "Grandfather",
            "Tabi Socks",
            "Dismantling",
            "Dick Growth",
            "Idol",
            "Eye Penetration",
            "Sketch Lines",
            "Sheep",
            "Kneesocks",
            "Kangaroo",
            "Animal On Furry",
            "Lion",
            "Bear",
            "Shark",
            "Straitjacket",
            "Anilingus",
            "Deer Girl",
            "Giraffe Girl",
            "Shark Boy",
            "Deer Boy",
            "Hyena Girl",
            "Happy Sex",
            "Dinosaur",
            "Food On Body",
            "Real Doll",
            "Gijinka",
            "Retractable Penis",
            "Multiple Vaginas",
            "Multiple Footjob",
            "Animal on Animal",
            "Otter Girl",
            "Ball-less Shemale",
            "Trap",
            "Long Gloves",
            "Crotchless",
            "Sole Futanari",
            "Netori",
            "Doll",
            "Unusual Eyebrows",
            "Male on Futanari",
            "Reverse Harem",
            "Futanari on Male",
            "Reverse Rape",
            "Birth",
            "Elder Sister",
            "Non-H",
            "Poor Grammar",
            "Gender Bender",
            "Imouto",
            "Bird Boy",
            "Frotting",
            "Lotion",
            "Demon Boy",
            "Snake Boy",
            "Cow Girl",
            "Tattoo",
            "Whale",
            "Love Hotel",
            "Reverse Netorare",
            "Onsen",
            "Comedy",
            "Licking",
            "Sixty-Nine",
            "Mask",
            "Stripping",
            "Bathroom Sex",
            "Futanari on Futanari",
            "Robot Girl",
            "Student",
            "Poor Translation",
            "Softcore",
            "Dirty Old Man",
            "Caption",
            "Superhero",
            "Fish",
            "Spitroast",
            "Maledom",
            "Symbol Shaped Pupils",
            "Egg Laying",
            "Threesome",
            "Futa on Male",
            "Human Pet",
            "Watersports",
            "Beach Sex",
            "School Uniform",
            "Panther"
        
        ]

# Initialize a counter for total combinations
total_combinations = 0

# Generate combinations of tags for sizes 2 and 3
for r in range(2, len(tags) + 1):
    
    combinations = list(itertools.combinations(tags, r))  # Generate combinations
    total_combinations += len(combinations)  # Update the counter with the length of combinations

# Print the total number of combinations
print(total_combinations)
