name: Scrape   Data and Save to MongoDB
on: [push]


jobs:
  scrape:
    runs-on: ubuntu-latest  # You can also use other environments such as windows-latest, if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install the required packages directly
          pip install beautifulsoup4 selenium pymongo
        
      - name: Run get-save-data.py script
        env:
          MONGO_URl: ${{ secrets.MONGO_URl }}
        run: |
          python get-save-data.py
